# Module 5: Route Efficiency Benchmarking

In [2]:
import pandas as pd
import numpy as np

In [ ]:
# Load Feature Engineered Dataset

df = pd.read_csv("../data/processed/feature_engineered_dataset.csv")

In [5]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,...,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Shipping Lead Time,Factory,Factory_to_State,Factory_to_Region
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,...,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,909,Wicked Choccy's,Wicked Choccy's → Texas,Wicked Choccy's → Interior
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,909,Wicked Choccy's,Wicked Choccy's → Illinois,Wicked Choccy's → Interior
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,909,Lot's O' Nuts,Lot's O' Nuts → Illinois,Lot's O' Nuts → Interior
3,4,US-2021-112326-CHO-SCR-58000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,909,Lot's O' Nuts,Lot's O' Nuts → Illinois,Lot's O' Nuts → Interior
4,5,US-2021-141817-CHO-TRI-54000,2024-01-05,2026-07-05,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,...,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,912,Wicked Choccy's,Wicked Choccy's → Pennsylvania,Wicked Choccy's → Atlantic

In [6]:
# Route Summary
route_summary = (
    df.groupby("Factory_to_State")
      .agg(
          Shipment_Count=("Shipping Lead Time", "count"),
          Average_Lead_Time=("Shipping Lead Time", "mean"),
          Minimum_Lead_Time=("Shipping Lead Time", "min"),
          Maximum_Lead_Time=("Shipping Lead Time", "max")
      )
      .reset_index()
)

route_summary.head()

,Factory_to_State,Shipment_Count,Average_Lead_Time,Minimum_Lead_Time,Maximum_Lead_Time
0,Lot's O' Nuts → Alabama,34,1295.205882,906,1642
1,Lot's O' Nuts → Alberta,16,1273.875000,909,1640
2,Lot's O' Nuts → Arizona,111,1306.198198,904,1642
3,Lot's O' Nuts → Arkansas,31,1285.354839,908,1642
4,Lot's O' Nuts → British Columbia,18,1273.777778,906,1640

In [12]:
# Fastest Routes
fastest_routes = route_summary.sort_values(
    by="Average_Lead_Time",
    ascending=True
)

fastest_routes.head(10)

,Factory_to_State,Shipment_Count,Average_Lead_Time,Minimum_Lead_Time,Maximum_Lead_Time,Route_Rank
80,Secret Factory → New Mexico,2,906.0,904,908,1.0
76,Secret Factory → Nebraska,1,906.0,906,906,1.0
121,The Other Factory → Louisiana,1,907.0,907,907,2.0
115,The Other Factory → Connecticut,2,907.5,906,909,3.0
75,Secret Factory → Mississippi,1,908.0,908,908,4.0
158,Wicked Choccy's → Maine,2,908.0,908,908,4.0
70,Secret Factory → Louisiana,2,908.5,908,909,5.0
64,Secret Factory → Delaware,1,909.0,909,909,6.0
88,Secret Factory → South Carolina,1,909.0,909,909,6.0
74,Secret Factory → Minnesota,1,909.0,909,909,6.0

In [7]:
# Slowest Routes
slowest_routes = route_summary.sort_values(
    by="Average_Lead_Time",
    ascending=False
)

slowest_routes.head(10)

,Factory_to_State,Shipment_Count,Average_Lead_Time,Minimum_Lead_Time,Maximum_Lead_Time
103,Sugar Shack → New Jersey,1,1642.0,1642,1642
78,Secret Factory → New Hampshire,1,1641.0,1641,1641
98,Sugar Shack → Connecticut,1,1641.0,1641,1641
194,Wicked Choccy's → West Virginia,2,1639.0,1639,1639
37,Lot's O' Nuts → North Dakota,5,1638.2,1637,1640
97,Sugar Shack → California,1,1638.0,1638,1638
125,The Other Factory → Nevada,1,1638.0,1638,1638
110,Sugar Shack → Washington,1,1638.0,1638,1638
63,Secret Factory → Connecticut,1,1638.0,1638,1638
105,Sugar Shack → Ohio,2,1637.5,1635,1640

In [8]:
# Route Ranking
route_summary["Route_Rank"] = (
    route_summary["Average_Lead_Time"]
    .rank(method="dense", ascending=True)
)

route_summary.head()

,Factory_to_State,Shipment_Count,Average_Lead_Time,Minimum_Lead_Time,Maximum_Lead_Time,Route_Rank
0,Lot's O' Nuts → Alabama,34,1295.205882,906,1642,62.0
1,Lot's O' Nuts → Alberta,16,1273.875000,909,1640,52.0
2,Lot's O' Nuts → Arizona,111,1306.198198,904,1642,70.0
3,Lot's O' Nuts → Arkansas,31,1285.354839,908,1642,58.0
4,Lot's O' Nuts → British Columbia,18,1273.777778,906,1640,51.0

In [13]:
# Top 10 Efficient Routes
top10_fastest = fastest_routes.head(10)

top10_fastest

,Factory_to_State,Shipment_Count,Average_Lead_Time,Minimum_Lead_Time,Maximum_Lead_Time,Route_Rank
80,Secret Factory → New Mexico,2,906.0,904,908,1.0
76,Secret Factory → Nebraska,1,906.0,906,906,1.0
121,The Other Factory → Louisiana,1,907.0,907,907,2.0
115,The Other Factory → Connecticut,2,907.5,906,909,3.0
75,Secret Factory → Mississippi,1,908.0,908,908,4.0
158,Wicked Choccy's → Maine,2,908.0,908,908,4.0
70,Secret Factory → Louisiana,2,908.5,908,909,5.0
64,Secret Factory → Delaware,1,909.0,909,909,6.0
88,Secret Factory → South Carolina,1,909.0,909,909,6.0
74,Secret Factory → Minnesota,1,909.0,909,909,6.0

In [14]:
# Bottom 10 Efficient Routes
bottom10_routes = slowest_routes.head(10)

bottom10_routes

,Factory_to_State,Shipment_Count,Average_Lead_Time,Minimum_Lead_Time,Maximum_Lead_Time
103,Sugar Shack → New Jersey,1,1642.0,1642,1642
78,Secret Factory → New Hampshire,1,1641.0,1641,1641
98,Sugar Shack → Connecticut,1,1641.0,1641,1641
194,Wicked Choccy's → West Virginia,2,1639.0,1639,1639
37,Lot's O' Nuts → North Dakota,5,1638.2,1637,1640
97,Sugar Shack → California,1,1638.0,1638,1638
125,The Other Factory → Nevada,1,1638.0,1638,1638
110,Sugar Shack → Washington,1,1638.0,1638,1638
63,Secret Factory → Connecticut,1,1638.0,1638,1638
105,Sugar Shack → Ohio,2,1637.5,1635,1640

In [15]:
# Overall Statistics
route_summary.describe()

,Shipment_Count,Average_Lead_Time,Minimum_Lead_Time,Maximum_Lead_Time,Route_Rank
count,196.000000,196.000000,196.000000,196.000000,196.000000
mean,52.010204,1314.045077,1040.841837,1548.816327,81.852041
std,130.352067,154.577405,224.784570,201.053755,49.044653
min,1.000000,906.000000,904.000000,906.000000,1.000000
25%,2.000000,1272.835044,906.000000,1638.000000,42.750000
50%,9.000000,1314.055556,908.000000,1640.000000,78.500000
75%,41.000000,1376.892857,1271.000000,1642.000000,126.250000
max,1125.000000,1642.000000,1642.000000,1642.000000,164.000000

In [22]:
top10_fastest = fastest_routes.head(10)
top10_slowest = slowest_routes.head(10)

In [23]:
# Save Results

route_summary.to_csv(
    "../data/processed/route_efficiency_benchmark.csv",
    index=False
)

top10_fastest.to_csv(
    "../data/processed/top10_fastest_routes.csv",
    index=False
)

top10_slowest.to_csv(
    "../data/processed/top10_slowest_routes.csv",
    index=False
)

### Observation

- Route-wise efficiency benchmark generated.
- Fastest and slowest routes identified.
- Route ranking completed.
- Benchmark reports saved successfully.